### ISSUE TITLE
Install a package using pip in Conda.jl

### ISSUE THREAD

**Issue by finmod** [JuliaPy/Conda.jl#101] opened 2018-01-15 10:50 UTC
How do I install a package, which is not in the continuum repos, using pip:

In python, it would like to install pycma as follows:

pip install -e cma or 
pip install git+https://github.com/CMA-ES/pycma.git@master

Conda.list() tells me that pip is already installed.

What is the syntax for Conda.add() in Julia?

> using Conda
> Conda. add("")

**Comment by stevengj** [comment] 2018-06-13 18:58
Duplicate of #50.

**Closed by stevengj** 2018-06-13 18:58 UTC
