### ISSUE TITLE
LoadError: UndefVarError: MINICONDA_VERSION not defined

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaPy/Conda.jl#88] opened 2017-07-31 19:44 UTC
```julia
julia> Pkg.build("Conda")
INFO: Building Conda
================================[ ERROR: Conda ]================================

LoadError: UndefVarError: MINICONDA_VERSION not defined
while loading /Users/solver/.julia/v0.6/Conda/deps/build.jl, in expression starting on line 13

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Conda had build errors.

 - packages with build errors remain installed in /Users/solver/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("Conda")`
 - build a single package by running its `deps/build.jl` script

================================================================================

julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.7.0)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libgfortblas
  LAPACK: liblapack
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

**Comment by mkborregaard** [comment] 2017-07-31 20:13
me too

**Comment by davidanthoff** [comment] 2017-07-31 20:37
me too. Windows 10, julia 0.6.

**Comment by nadesai** [comment] 2017-07-31 21:08
Me as well.
```
julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, sandybridge)
```

**Comment by stillyslalom** [comment] 2017-08-01 01:22
Looks like a duplicate of #85. `Pkg.checkout("Conda")` works as a temporary fix until a new release is tagged.

**Comment by isuruf** [comment] 2017-08-02 15:03
This should now be fixed with the latest release

**Closed** 2018-06-13 18:57 UTC
