### ISSUE TITLE
GLIBCXX version problem with scipy.optimize on Linux

### ISSUE THREAD

**Issue by oschulz** [JuliaPy/Conda.jl#226] opened 2022-11-02 21:09 UTC
I'm reporting this here though I'm not sure it's Conda.jl's fault directly, but I'm not sure where else to open this issue ...

On a clean Linux system (Ubuntu 20.04) with an empty `.julia` directory, accessing `scipy.optimize` fails after installing scipy via `PyCall.pyimport_conda("scipy", "scipy")` due to a GLIBCXX version problem:

```julia
julia> ENV["PYTHON"]="Conda"
"Conda"

(@v1.8) pkg> add PyCall

...

julia> using PyCall

julia> scipy = pyimport_conda("scipy", "scipy")
[ Info: Installing scipy via the Conda scipy package...
[ Info: Running `conda install -y scipy` in root environment
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/user/.julia/conda/3

  added / updated specs:
    - scipy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    scipy-1.9.3                |  py310hdfbd76f_1        26.2 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        26.2 MB

The following NEW packages will be INSTALLED:

  scipy              conda-forge/linux-64::scipy-1.9.3-py310hdfbd76f_1 None

...

julia> scipy.optimize
ERROR: PyError (PyObject_GetAttrString) <class 'ImportError'>
ImportError("/path/to/julia-1.8/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/user/.julia/conda/3/lib/python3.10/site-packages/scipy/optimize/_highs/_highs_wrapper.cpython-310-x86_64-linux-gnu.so)")
  File "/home/user/.julia/conda/3/lib/python3.10/site-packages/scipy/__init__.py", line 211, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/home/user/.julia/conda/3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/.julia/conda/3/lib/python3.10/site-packages/scipy/optimize/__init__.py", line 413, in <module>
    from ._linprog import linprog, linprog_verbose_callback
  File "/home/user/.julia/conda/3/lib/python3.10/site-packages/scipy/optimize/_linprog.py", line 21, in <module>
    from ._linprog_highs import _linprog_highs
  File "/home/user/.julia/conda/3/lib/python3.10/site-packages/scipy/optimize/_linprog_highs.py", line 20, in <module>
    from ._highs._highs_wrapper import _highs_wrapper

Stacktrace:
 [1] _getproperty(o::PyObject, s::Symbol)
   @ PyCall /home/user/.julia/packages/PyCall/ygXW2/src/PyCall.jl:304
 [2] __getproperty
   @ /home/user/.julia/packages/PyCall/ygXW2/src/PyCall.jl:312 [inlined]
 [3] getproperty(o::PyObject, s::Symbol)
   @ PyCall /home/user/.julia/packages/PyCall/ygXW2/src/PyCall.jl:318
 [4] top-level scope
   @ REPL[6]:1

julia> versioninfo()
Julia Version 1.8.2
Commit 36034abf260 (2022-09-29 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 6 on 12 virtual cores
```

CC @Cornelius-G , who ran into this as well.

**Comment by devmotion** [comment] 2023-01-25 10:48
Did you figure out a solution? I encountered this issue as well in some CI run this morning.

**Comment by devmotion** [comment] 2023-01-25 10:53
Ah, seems to be a duplicate of https://github.com/JuliaPy/Conda.jl/issues/224 and https://github.com/JuliaPy/PyCall.jl/issues/999.

**Comment by stevengj** [comment] 2023-01-25 12:58
Closing as a dup.  As I commented in the PyCall issue, there's not much we can do about this.

**Closed by stevengj** 2023-01-25 12:58 UTC
